application: catholicmissale
version: 1
runtime: python27
api_version: 1
threadsafe: yes
 
handlers:
- url: /.*
  script: main.app
   
libraries:
- name: webapp2
  version: "2.5.1" 
- name: jinja2
  version: latest
- name: pycrypto
  version: latest